Pelin
erkalicious/sensor-simulator pull request #5
Opened 2016-11-23 03:12 UTC by Pelin89

Initiation of DEEPs.

2016-11-23 15:38 UTC, ericbf requested changes
You’ve got the right idea with most of this! I’ll push a few changes, if that’s okay?

2016-11-23 15:49 UTC, Pelin89 commented
Sure! Go ahead.

On Wed, Nov 23, 2016 at 10:38 AM erkalicious <notifications@github.com>
wrote:

> *@erkalicious* requested changes on this pull request.
>
> You’ve got the right idea with most of this! I’ll push a few changes, if
> that’s okay?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/erkalicious/sensor-simulator/pull/5#pullrequestreview-9886534>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AV_tuAMlTKDSBty2pbWazntjTHkXDr4Iks5rBF4NgaJpZM4K6Lqa>
> .
>

2016-11-24 07:44 UTC, erkalicious commented
I push the changes. It's not perfect yet, as it doesn't complete the cover successfully, but see if you can follow the process? Let me know what you think, please

2016-11-27 14:07 UTC, ericbf approved these changes

2016-11-28 00:12 UTC, merged